### ISSUE TITLE
Publish `birdcage` to crates.io

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/birdcage#19]
This crate should be published to crates.io

**Comment by kylewillmon** [comment]
This crate currently relies on our own fork of `rust-landlock` as a git dependency. That is not allowed on crates.io and will need to be resolved.

Once landlock-lsm/rust-landlock#19 is merged and a new release of the upstream crate is published, we can use that.

**Comment by l0kod** [comment]
FYI, I plan to publish a new Landlock crate version next month.

**Comment by cd-work** [comment]
https://crates.io/crates/birdcage
