### ISSUE TITLE
Feature request: Restrict the current process

### ISSUE THREAD

**Issue by heinrich5991** [phylum-dev/birdcage#81]
I don't know if that's feasible with the current OS APIs used, but I'd like to restrict my own Rust process from accessing most of the filesystem **but only after initialization**, similar to how one would use [`pledge`](https://man.openbsd.org/pledge.2)/[`unveil`](https://man.openbsd.org/unveil.2) on OpenBSD.

**Comment by cd-work** [comment]
The problem with this is that certain types of isolation are not available without spawning a new process. A new PID namespace for example will only allow process isolation for the next process spawned inside it.

However you did mention you only want to restrict the filesystem and that is possible even on a per-thread basis. If it would be fine to solely sandbox the filesystem and only support Linux, then maybe you can just use https://crates.io/crates/landlock directly. Birdcage has used this in the past and as long as you only need relatively simple filesystem access it should work well and be pretty simple to use.

**Comment by heinrich5991** [comment]
Thanks for the quick answer. :)

**Comment by cd-work** [comment]
No problem, just let me know if you have any questions.
